src/Meowv.Blog.WebApp/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace Meowv.Blog.WebApp.Controllers
{
    public class AdminController : Controller
    {
        /// <summary>
        /// 鉴权
        /// </summary>
        /// <returns></returns>
        [Route("/account/auth")]
        public IActionResult Auth() => View();

        /// <summary>
        /// 后台管理
        /// </summary>
        /// <returns></returns>
        [Route("/admin")]
        public IActionResult Index() => View();

        /// <summary>
        /// 文章管理
        /// </summary>
        /// <returns></returns>
        [Route("/admin/posts")]
        [Route("/admin/posts/page/{page:int:min(1)}")]
        public IActionResult Posts() => View();

        /// <summary>
        /// 添加文章
        /// </summary>
        /// <returns></returns>
        [Route("/admin/add_post")]
        public IActionResult AddPost() => View();

        /// <summary>
        /// 编辑文章
        /// </summary>
        /// <returns></returns>
        [Route("/admin/edit_post/{id:int:min(1)}")]
        public IActionResult EditPost() => View();

        /// <summary>
        /// 分类管理
        /// </summary>
        /// <returns></returns>
        [Route("/admin/categories")]
        public IActionResult Categories() => View();

        /// <summary>
        /// 标签管理
        /// </summary>
        /// <returns></returns>
        [Route("/admin/tags")]
        public IActionResult Tags() => View();

        /// <summary>
        /// 标签列表页，用于添加和编辑文章时点选标签
        /// </summary>
        /// <returns></returns>
        [Route("/admin/tags/list")]
        public IActionResult TagsList() => View();

        /// <summary>
        /// 友情链接
        /// </summary>
        /// <returns></returns>
        [Route("/admin/friendlinks")]
        public IActionResult FriendLinks() => View();

        /// <summary>
        /// 图集管理
        /// </summary>
        /// <returns></returns>
        [Route("/admin/gallery")]
        public IActionResult Gallery() => View();

        /// <summary>
        /// Notification
        /// </summary>
        /// <returns></returns>
        [Route("/admin/notification")]
        public IActionResult Notification() => View();
    }
}

src/Meowv.Blog.WebApp/Controllers/AppsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Meowv.Blog.WebApp.Controllers
{
    public class AppsController : Controller
    {
        /// <summary>
        /// Apps
        /// </summary>
        /// <returns></returns>
        [Route("/apps")]
        public IActionResult Index() => View();

        /// <summary>
        /// 吐个槽
        /// </summary>
        /// <returns></returns>
        [Route("/tucao")]
        public IActionResult TuCao() => View();

        /// <summary>
        /// Signature
        /// </summary>
        /// <returns></returns>
        [Route("/sign")]
        public IActionResult Signature() => View();

        /// <summary>
        /// 每日热点
        /// </summary>
        /// <returns></returns>
        [Route("/hot")]
        public IActionResult Hot() => View();

        /// <summary>
        /// 随机妹子图
        /// </summary>
        /// <returns></returns>
        [Route("/girl")]
        public IActionResult Girl() => View();

        /// <summary>
        /// 随机猫咪图
        /// </summary>
        /// <returns></returns>
        [Route("/cat")]
        public IActionResult Cat() => View();

        /// <summary>
        /// Bing每日壁纸
        /// </summary>
        /// <returns></returns>
        [Route("/bing")]
        public IActionResult Bing() => View();

        /// <summary>
        /// Mta
        /// </summary>
        /// <returns></returns>
        [Route("/analysis")]
        public IActionResult Mta() => View();

        /// <summary>
        /// 友链
        /// </summary>
        /// <returns></returns>
        [Route("/friendlinks")]
        public IActionResult FriendLinks() => View();

        /// <summary>
        /// 图集相册
        /// </summary>
        /// <returns></returns>
        [Route("/gallery")]
        public IActionResult Gallery() => View();

        /// <summary>
        /// 毒鸡汤
        /// </summary>
        /// <returns></returns>
        [Route("/soul")]
        public IActionResult Soul() => View();

        /// <summary>
        /// 2048
        /// </summary>
        /// <returns></returns>
        [Route("/2048")]
        public IActionResult Game2048() => View();

        /// <summary>
        /// 壁纸
        /// </summary>
        /// <returns></returns>
        [Route("/wallpaper")]
        public IActionResult Wallpaper() => View();
    }
}

src/Meowv.Blog.WebApp/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;

namespace Meowv.Blog.WebApp.Controllers
{
    public class CategoriesController : Controller
    {
        /// <summary>
        /// 分类页
        /// </summary>
        /// <returns></returns>
        [Route("/categories")]
        public IActionResult Index() => View();

        /// <summary>
        /// 分类查询文章列表页
        /// </summary>
        /// <returns></returns>
        [Route("/category/{name}")]
        public IActionResult Category() => View();
    }
}

src/Meowv.Blog.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Meowv.Blog.WebApp.Controllers
{
    public class HomeController : Controller
    {
        /// <summary>
        /// 首页
        /// </summary>
        /// <returns></returns>
        [Route("/")]
        [Route("/index.html")]
        public IActionResult Index() => View();
    }
}

src/Meowv.Blog.WebApp/Controllers/PostsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Meowv.Blog.WebApp.Controllers
{
    public class PostsController : Controller
    {
        /// <summary>
        /// 文章列表页
        /// </summary>
        /// <returns></returns>
        [Route("/posts")]
        [Route("/posts/page/{page:int:min(1)}")]
        public IActionResult Index() => View();

        /// <summary>
        /// 文章详情页
        /// </summary>
        /// <returns></returns>
        [Route("/post/{year:int:min(2014):max(2024):length(4)}/{month:int:range(1,12)}/{day:int:range(1,31)}/{url}")]
        public IActionResult Detail() => View();
    }
}

src/Meowv.Blog.WebApp/Controllers/TagsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Meowv.Blog.WebApp.Controllers
{
    public class TagsController : Controller
    {
        /// <summary>
        /// 标签页
        /// </summary>
        /// <returns></returns>
        [Route("/tags")]
        public IActionResult Index() => View();

        /// <summary>
        /// 标签查询文章列表页
        /// </summary>
        /// <returns></returns>
        [Route("/tag/{name}")]
        public IActionResult Tag() => View();
    }
}

src/Meowv.Blog.WebApp/Views/Apps/Bing.cshtml
@{
    ViewData["Title"] = "Bing每日壁纸 - ";
}
<div class="main">
    <div class="loader"></div>
    <div class="container">
        <div class="imgbox">
            <img src="https://api.meowv.com/common/bing/" />
        </div>
    </div>
</div>

src/Meowv.Blog.WebApp/Views/Apps/Cat.cshtml
@{
    ViewData["Title"] = "随机猫咪图 - ";
}
<div class="main">
    <div class="loader"></div>
    <div class="container">
        <div class="imgbox">
            <img src="https://api.meowv.com/common/cat/" />
        </div>
    </div>
</div>

src/Meowv.Blog.WebApp/Views/Apps/FriendLinks.cshtml
@{
    ViewData["Title"] = "友情链接 - ";
}
<div class="main">
    <div class="container">
        <div class="post-wrap categories">
            <h2 class="post-title">-&nbsp;FriendLinks&nbsp;-</h2>
            <div class="categories-card">
                <script id="friendlinks_tmpl" type="text/template">
                    {{each result}}
                    <div class="card-item">
                        <div class="categories">
                            <a target="_blank" href="{{$value.linkUrl}}">
                                <h3> {{$value.title}}</h3>
                            </a>
                        </div>
                    </div>
                    {{/each}}
                </script>
            </div>
        </div>
    </div>
</div>
<div class="loader"></div>
@section scripts{
<script src="https://static.meowv.com/js/axios.min.js"></script>
<script src="https://static.meowv.com/js/template-web.js"></script>
}

src/Meowv.Blog.WebApp/Views/Apps/Gallery.cshtml
@{Layout = null;}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="keywords" content="Gallery，阿星Plus">
    <meta name="description" content="Gallery - 生命不息，奋斗不止">
    <title>😍Gallery - 阿星Plus⭐⭐⭐</title>
    <link rel="icon" href="https://static.meowv.com/favicon.ico">
    <link href="https://static.meowv.com/css/gallery.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <script id="gallery_tmpl" type="text/template">
            {{each result}}
            <div class="albums" data-id="{{$value.id}}" data-isPublic="{{$value.isPublic}}">
                <img src="{{$value.imgUrl}}" alt="{{$value.name}}" title="【{{$value.name}}】共 {{$value.count}} 张图片" />
            </div>
            {{/each}}
        </script>
    </div>
    <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="pswp__bg"></div>
        <div class="pswp__scroll-wrap">
            <div class="pswp__container">
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
            </div>
            <div class="pswp__ui pswp__ui--hidden">
                <div class="pswp__top-bar">
                    <div class="pswp__counter"></div>
                    <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
                    <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
                    <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
                    <div class="pswp__preloader">
                        <div class="pswp__preloader__icn">
                            <div class="pswp__preloader__cut">
                                <div class="pswp__preloader__donut"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                    <div class="pswp__share-tooltip"></div>
                </div>
                <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
                </button>
                <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
                </button>
                <div class="pswp__caption">
                    <div class="pswp__caption__center"></div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
<script src="https://static.meowv.com/js/axios.min.js"></script>
<script src="https://static.meowv.com/js/template-web.js"></script>
<script src="https://static.meowv.com/photoswipe/photoswipe.min.js"></script>
<script src="https://static.meowv.com/photoswipe/photoswipe-ui-default.min.js"></script>
<environment include="Development"><script src="~/js/gallery.js"></script></environment>
<environment exclude="Development"><script src="https://static.meowv.com/js/gallery.min.js"></script></environment>

src/Meowv.Blog.WebApp/Views/Apps/Game2048.cshtml
@{Layout = null;}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="keywords" content="Gallery，阿星Plus">
    <meta name="description" content="Gallery - 生命不息，奋斗不止">
    <title>😍程序员版2048 - 阿星Plus⭐⭐⭐</title>
    <link rel="icon" href="https://static.meowv.com/favicon.ico">
    <link href="https://static.meowv.com/css/2048.min.css" rel="stylesheet" />
    <script src="https://static.meowv.com/js/2048.min.js"></script>
</head>
<body>
    <div class=container><div class=heading><h1 class="title">2048</h1><div class=scores-container><div class=score-container><div class=score-addition></div></div><div class=best-container></div></div></div><div class=above-game><a class=links href=/apps>← 返回</a><a class=restart-button>新游戏</a></div><div class=game-container><div class=game-message><p></p><div class=lower><a class=keep-playing-button>继续前进</a><a class=retry-button>再试一次</a><div class=score-sharing></div></div></div><div class=grid-container><div class=grid-row><div class=grid-cell></div><div class=grid-cell></div><div class=grid-cell></div><div class=grid-cell></div></div><div class=grid-row><div class=grid-cell></div><div class=grid-cell></div><div class=grid-cell></div><div class=grid-cell></div></div><div class=grid-row><div class=grid-cell></div><div class=grid-cell></div><div class=grid-cell></div><div class=grid-cell></div></div><div class=grid-row><div class=grid-cell></div><div class=grid-cell></div><div class=grid-cell></div><div class=grid-cell></div></div></div><div class=tile-container></div></div></div>
</body>
</html>

src/Meowv.Blog.WebApp/Views/Apps/Girl.cshtml
@{
    ViewData["Title"] = "随机妹子图 - ";
}
<div class="main">
    <div class="loader"></div>
    <div class="container">
        <div class="imgbox girl-img">
            <img src="https://api.meowv.com/common/girl/" />
        </div>
        <div class="girl-qrcode">
            <img src="https://static.meowv.com/images/girl_qrcode.jpg" />
        </div>
        <div class="btnbox">
            <button class="soul-btn">再来一个妹子</button>
        </div>
    </div>
</div>

src/Meowv.Blog.WebApp/Views/Apps/Hot.cshtml
@{
    ViewData["Title"] = "每日热点 - ";
}
<div class="main">
    <div class="container tab-box">
        <div class="top-tab">
            <script id="top_tabs_tmpl" type="text/template">
                {{each result}}
                <li><a href="javascript:;" data-id="{{$value.value}}">{{$value.description}}</a></li>
                {{/each}}
            </script>
            <ul></ul>
        </div>
        <div class="top-content">
            <div class="loader"></div>
            <script id="top_content_tmpl" type="text/template">
                {{each result}}
                <li><a target="_blank" href="{{$value.url}}">{{$value.title==''?$value.url:$value.title}}</a></li>
                {{/each}}
            </script>
            <ul></ul>
        </div>
    </div>
</div>
@section scripts{
<script src="https://static.meowv.com/js/axios.min.js"></script>
<script src="https://static.meowv.com/js/template-web.js"></script>
}

src/Meowv.Blog.WebApp/Views/Apps/Index.cshtml
@{
    ViewData["Title"] = "Apps - ";
}
<div class="main">
    <div class="container">
        <div class="post-wrap">
            <h2 class="post-title">-&nbsp;Apps&nbsp;-</h2>
            <ul>
                <li>
                    <a asp-controller="Apps" asp-action="TuCao"><h3>吐个槽(留言板)</h3></a>
                </li>
                <li>
                    <a asp-controller="Apps" asp-action="Signature"><h3>个性艺术签名设计</h3></a>
                </li>
                <li>
                    <a asp-controller="Apps" asp-action="Wallpaper"><h3>手机壁纸</h3></a>
                </li>
                <li>
                    <a asp-controller="Apps" asp-action="Game2048"><h3>程序员版2048</h3></a>
                </li>
                <li>
                    <a asp-controller="Apps" asp-action="Hot"><h3>每日热点</h3></a>
                </li>
                <li>
                    <a asp-controller="Apps" asp-action="Gallery"><h3>图集相册</h3></a>
                </li>
                <li>
                    <a asp-controller="Apps" asp-action="Soul"><h3>毒鸡汤</h3></a>
                </li>
                <li>
                    <a asp-controller="Apps" asp-action="Girl"><h3>随机妹子图</h3></a>
                </li>
                <li>
                    <a asp-controller="Apps" asp-action="Cat"><h3>随机猫咪图</h3></a>
                </li>
                <li>
                    <a asp-controller="Apps" asp-action="Bing"><h3>每日壁纸</h3></a>
                </li>
                <li>
                    <a asp-controller="Apps" asp-action="Mta"><h3>访问数据分析</h3></a>
                </li>
                <li>
                    <a asp-controller="Apps" asp-action="FriendLinks"><h3>友情链接</h3></a>
                </li>
                <li>
                    <a href="javascript:;" id="change_song_list"><h3>换一批歌单</h3></a>
                </li>
            </ul>
        </div>
    </div>
</div>

src/Meowv.Blog.WebApp/Views/Apps/Mta.cshtml
@{
    ViewData["Title"] = "访问数据分析 - ";
}
<div class="main">
    <div class="mta-box">
        <div class="mta-a">
            <div class="loader"></div>
            <ul>
                <li>
                    <div class="mta-a-item">
                        <div class="mta-a-title">
                            浏览量(PV)
                        </div>
                        <div class="mta-a-value" id="pv">
                            <strong>888888</strong>
                        </div>
                        <div class="mta-date"></div>
                    </div>
                </li>
                <li>
                    <div class="mta-a-item">
                        <div class="mta-a-title">
                            独立用户(UV)
                        </div>
                        <div class="mta-a-value" id="uv">
                            <strong>888888</strong>
                        </div>
                        <div class="mta-date"></div>
                    </div>
                </li>
                <li>
                    <div class="mta-a-item">
                        <div class="mta-a-title">
                            访问次数(VV)
                        </div>
                        <div class="mta-a-value" id="vv">
                            <strong>888888</strong>
                        </div>
                        <div class="mta-date"></div>
                    </div>
                </li>
                <li>
                    <div class="mta-a-item">
                        <div class="mta-a-title">
                            独立IP
                        </div>
                        <div class="mta-a-value" id="iv">
                            <strong>888888</strong>
                        </div>
                        <div class="mta-date"></div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
@section scripts{
<script src="https://static.meowv.com/js/axios.min.js"></script>
}

src/Meowv.Blog.WebApp/Views/Apps/Signature.cshtml
@{
    ViewData["Title"] = "个性艺术签名设计 - ";
}
<div class="main">
    <div class="container">
        <div class="loader"></div>
        <div class="signature-box hidden">
            <p>图片仅保留24小时，如有需要请尽快下载，请勿频繁调用，谢谢！</p>
            <div class="signature-img">
                <img src="https://static.meowv.com/images/wxcode.jpg" />
            </div>
            <div class="signature-action">
                <select id="type"></select>
                <input type="text" id="name" placeholder="输入你的名字，1-4个字符" maxlength="4" autocomplete="off" value="" />
                <button id="btn_do">免费设计</button>
            </div>
        </div>
        <div class="post-wrap tags hidden">
            <h3>-&nbsp;最近设计的签名&nbsp;-</h3>
            <div class="tag-cloud-tags tag-cloud-tags-extend"></div>
        </div>
    </div>
</div>
@section scripts{
<script src="https://static.meowv.com/js/axios.min.js"></script>
<script src="https://ssl.captcha.qq.com/TCaptcha.js"></script>
}

src/Meowv.Blog.WebApp/Views/Apps/Soul.cshtml
@{
    ViewData["Title"] = "毒鸡汤 - ";
}
<div class="main">
    <div class="container">
        <div class="soul"><h1>毒鸡汤~</h1></div>
        <div class="soul"><button class="soul-btn">再来一碗</button></div>
    </div>
</div>
@section scripts{
<script src="https://static.meowv.com/js/axios.min.js"></script>
}

src/Meowv.Blog.WebApp/Views/Apps/TuCao.cshtml
@{
    ViewData["Title"] = "吐个槽 - ";
}
<div class="main" style="margin-top: 10px;">
    <iframe id="tucao" frameborder="0" width="100%" height="747" src="https://support.qq.com/products/75616"></iframe>
</div>

src/Meowv.Blog.WebApp/Views/Apps/Wallpaper.cshtml
@{
    ViewData["Title"] = "手机壁纸 - ";
}
<div class="main">
    <div class="loader"></div>
    <div class="wallpaper-container">
        <div class="plus-container">
            <p class="wallpaper-nav">
                <script id="wallpaper_nav_tmpl" type="text/template">
                    {{each result}}
                    <a href="javascript:;" data-type="{{$value.value}}">{{$value.description}}</a>
                    {{/each}}
                </script>
            </p>
            <div class="wallpapers plus-row plus-col-space20">
                <script id="wallpaper_tmpl" type="text/template">
                    {{each result}}
                    <div class="plus-col-xs6 plus-col-md2">
                        <div class="wallpaper">
                            <img src="{{$value.url.replace("max","middle")}}" title="{{$value.title}}" alt="{{$value.title}}" />
                        </div>
                    </div>
                    {{/each}}
                </script>
            </div>
        </div>
        <nav class="pagination"></nav>
    </div>
</div>
@section scripts{
<script src="https://static.meowv.com/js/axios.min.js"></script>
<script src="https://static.meowv.com/js/template-web.js"></script>
}

src/Meowv.Blog.WebApp/Views/Categories/Category.cshtml
<div class="main">
    <div class="container">
        <div class="post-wrap tags">
            <h2 class="post-title">
                <script id="categoryName_tmpl" type="text/template">
                    -&nbsp;Category&nbsp;·&nbsp;{{@@result}}&nbsp;-
                </script>
            </h2>
        </div>
        <div class="post-wrap archive">
            <script id="category_post_tmpl" type="text/template">
                {{each result}}
                <h3>{{$value.year}}</h3>
                {{each $value.posts}}
                <article class="archive-item">
                    <a class="archive-item-link" href="/post{{$value.url}}">{{$value.title}}</a>
                    <span class="archive-item-date">{{$value.creationTime}}</span>
                </article>
                {{/each}}
                {{/each}}
            </script>
        </div>
    </div>
    <div class="loader"></div>
</div>
@section scripts{
<script src="https://static.meowv.com/js/axios.min.js"></script>
<script src="https://static.meowv.com/js/template-web.js"></script>
}

src/Meowv.Blog.WebApp/Views/Categories/Index.cshtml
@{
    ViewData["Title"] = "Categories - ";
}
<div class="main">
    <div class="container">
        <div class="post-wrap categories">
            <h2 class="post-title">-&nbsp;Categories&nbsp;-</h2>
            <div class="categories-card">
                <script id="categories_tmpl" type="text/template">
                    {{each result}}
                    <div class="card-item">
                        <div class="categories">
                            <a href="/category/{{$value.displayName}}/">
                                <h3>
                                    <i class="iconfont iconcode" style="padding-right:3px"></i>
                                    {{$value.categoryName}}
                                </h3>
                                <small>({{$value.count}})</small>
                            </a>
                        </div>
                    </div>
                    {{/each}}
                </script>
            </div>
        </div>
    </div>
</div>
<div class="loader"></div>
@section scripts{
<script src="https://static.meowv.com/js/axios.min.js"></script>
<script src="https://static.meowv.com/js/template-web.js"></script>
}

src/Meowv.Blog.WebApp/Views/Home/Index.cshtml
<div class="main">
    <div class="container">
        <div class="intro">
            <div class="avatar">
                <a href="javascript:;"><img src="https://static.meowv.com/images/avatar.jpg"></a>
            </div>
            <div class="nickname">阿星Plus</div>
            <div class="description">
                <p>
                    生命不息，奋斗不止
                    <br>Cease to struggle and you cease to live
                </p>
            </div>
            <div class="links">
                <a class="link-item" title="Blog" href="/posts">
                    <i class="iconfont iconread"></i>
                </a>
                <a target="_blank" class="link-item" title="Notes" href="https://notes.meowv.com/">
                    <i class="iconfont iconnotes"></i>
                </a>
                <a target="_blank" class="link-item" title="API" href="https://api.meowv.com/">
                    <i class="iconfont iconapi"></i>
                </a>
                <a class="link-item" title="Manage" href="/account/auth">
                    <i class="iconfont iconcode"></i>
                </a>
                <a target="_blank" class="link-item" title="Github" href="https://github.com/Meowv/">
                    <i class="iconfont icongithub"></i>
                </a>
                <a class="link-item weixin" title="点击关注阿星Plus，带你飙车不迷路" href="javascript:;">
                    <i class="iconfont iconweixin">
                    </i>
                </a>
                <div class="qrcode hidden">
                    <img src="https://static.meowv.com/images/wx_qrcode.jpg" />
                </div>
            </div>
        </div>
    </div>
    <iframe src="https://api.meowv.com/common/tts" allow="autoplay" style="display:none;"></iframe>
</div>